data_directory: /students/2023-2024/Thema11/jotolhuis_snakemake
results_directory: /students/2023-2024/Thema11/jotolhuis_snakemake/results

genome: GCA_000001405.15_GRCh38_no_alt_analysis_set.fa

repeats: pathogenic_repeats.hg38.bed

barcodes: barcodes.fasta

repeat_id: DMPK

threads: 12

sort_threads: 4

trgt_threads: 12